#!/bin/bash
menu(){
echo -e '\0033\0143'

read -p " 

Funzioni Gestione Attivita':

1  -  Ping test
2  -  Utilizzo CPU
3  -  Utilizzo real-time della rete (Ctrl+C per terminare)
4  -  Spazio su Disco
5  -  Numero di processi
6  -  Memoria in uso
7  -  Istanza di tutti i processi
8  -  Ricerca di un processo
9  -  Processi real-time (Ctrl+C per terminare)
10 -  Dispositivi USB collegati
11 -  Informazioni sul computer
Inserisci il numero della funzione da avviare: " num

case $num in 
	1) read -p "Inserisci il dominio da pingare "  dominio
	   ping -c 5 $dominio | tail -2
	   pause
	   menu ;;
	2) top -bn1 | grep "Cpu(s)"
	   pause
	   menu ;;
	3) read -p "
Per utilizzare questa funzione e' necessario installare il pacchetto Nload. 
Procedere all'installazione? Y/N " s
	   if [ "$s" = "Y" -o "$s" = "y" ]
	   then
	  	 echo "Verra' avviata l'installazione: "
	  	 sudo apt-get install nload
	   	nload
           else
	  	 nload
           fi
           menu ;;
	4) df -h
	   pause 
	   menu;;
	5) top -bn1 | grep "Tasks"
	   pause 
	   menu ;;
	6) top -bn1 | grep "Mem"
	   pause 
	   menu ;;
	7) ps -A
	   pause
           menu ;;
	8) read -p "Inserisci il nome dal processo da ricercare: " nomeprocesso 
	   echo "
 PID	TTY    Durata   Nome"
	   ps -A | grep $nomeprocesso
	   pause
 	   menu ;;
	9) top
	   menu ;;
	10) lsusb 
	    pause
	    menu ;;
	11) read -p "
Questo e' il sottomenu' per le informazioni inerenti al computer:
1  -  CPU

Scegli di quale componente vuoi sapere di piu':" sceltainfo
	    case $sceltainfo in
	1) lscpu
	   pause
	   menu ;;
	   esac
esac

}

menu
